[project]
name = "func_cache"
version = "0.0.1"
description = "cache decorator for functions"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["setuptools>=75.1.0"]

[tool.uv.sources]
func-cache = { workspace = true }
