[project]
name = "func_cache"
version = "0.1.1"
description = "Cache decorator for functions"
readme = "README.md"
requires-python = ">=3.6"
dependencies = []

[tool.uv.sources]
func-cache = { workspace = true }
